# -*- coding: utf-8 -*-
"""agungor_the1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p-sVh0N2KmMcAV6AdxIqa_W7V2NU20Qh
"""

size = float(input("Please enter the file size you want to share in GB: " ))
upload_speed = float(input("Please enter your upload speed in Mbps: "))
download_speed = float(input("Please enter your friends download speed in Mbps: "))
total_second = 0
total_second += (size * 1024) 
compressed = (size * 38) / 100
total_second += (compressed * 1024 * 8) / upload_speed 
total_second += (compressed * 1024 *8) / download_speed
total_second += (compressed * 1024) / 1.2 
total_hour = int(total_second/3600)
total_min = int((total_second - (total_hour * 3600)) / 60)
final_sec = float(total_second - (total_hour * 3600) - (total_min * 60))
print("File sharing will take", total_hour, "hour(s),", total_min, "minute(s) and", format(final_sec, ".2f"), "second(s).")

"""Alperen GUNGOR - 28847"""